### ISSUE TITLE
Update README travis appveyor etc. 

### ISSUE THREAD

**Issue by dirvine** [maidsafe/memory_map#2]
Can we look at travis appveyor and coveralls as well as docs and so on. @Fraser999 and @rossmuir know the score there. We will use appveyor for libs that we don't intend to update often. Also add dev@maidsafe.net to Cargo.toml etc.

**Comment by s-brian** [comment]
Mainly done with https://github.com/maidsafe/memory_map/pull/3 I think, needs relevant hooks for CI to be put in the repo.
