### ISSUE TITLE
copyright & license

### ISSUE THREAD

**Issue by danburkert** [maidsafe/memory_map#20]
Hi, it appears that you have forked my repository and distributed it as a new crate with a GPL license.  My code is not (nor ever was) GPL licensed, however it is (now) licensed under ASL-2/MIT.  Please update your repository and crate to take this into account.

Additionally, I would like to let you know that I am happy to take contributions.

**Comment by brian-js** [comment]
Hi, thanks for letting us know about the license. It would be preferable to use your version and issue PR's if it is published to crates, are you planning on doing that?

**Comment by retep998** [comment]
@danburkert 's crate is indeed on crates.io.
https://crates.io/crates/memmap

**Comment by brian-js** [comment]
Great, thanks.

**Comment by danburkert** [comment]
Yep, my version is now published and I'm happy to take PRs.  The API has
changed somewhat since you forked, but it's not too different.   I don't
foresee the API changing much again.

**Comment by danburkert** [comment]
I guess my original message was not clear.  You continue to republish my work without including the proper licenses (ASL-2/MIT) . Additionally, you are representing my work as being distributed under a GPL license, despite not having the right to do so.  I ask you again: please update your repository and crate to take this into account.  The next time I ask will not be through a GitHub issue.

**Comment by dirvine** [comment]
I am sorry about this, there is no attempt to mis-represent in any way. We will get the licence changed immediately and then look at any differences and try and get on the crates version if possible. It's in our interests to use your crate, particularly as you are maintaining that. @rossmuir  can you prioritise this and check if we cannot push an unmaintained message to our crate and use @danburkert crate instead in our repo's please. 
Thanks for the efforts @danburkert we do appreciate the crate and are happy to use and PR to the original. We have more than enough work to get on with without maintaining / copying existing crates unless it's necessary for some reason. Sometimes we have had to make temp crates if we cannot get changes quick enough and that id fine. We would not intentionally change a license as a business and I am not sure here what happened, speed I guess but we will sort that out anyway.

**Comment by danburkert** [comment]
Thank you.

**Comment by dirvine** [comment]
No worries, it was our fault for not being focussed enough there, will get fixed today though @rossmuir  will update this issue when it's done.

**Comment by rossmuir** [comment]
Hi @danburkert sorry I have not managed to get to this today - I will pick this up tomorrow or @maqi

**Comment by maqi** [comment]
self_encryption's dependency on memory_map is now being changed to use the memmap crate,
in the PR of https://github.com/maidsafe/self_encryption/pull/137 

This issue can be closed once the PR get merged.

**Comment by Fraser999** [comment]
We're now using the original memmap crate, so this fork will shortly be deleted.  @danburkert - apologies again for the delay in actioning this, and thanks for your crate.
